import { Inter } from "next/font/google";
import "./globals.css";
import axios from "@/utils/axios";

const inter = Inter({ subsets: ["latin"] });

const getMetaData = async () => {

  try {
    const response = await axios.get("/page/home", {
      headers: {
        "Accept-Language": "en", 
      },
    });
    return response.data;
  } catch (err) {
    console.error(err);
  }
};

const data = await getMetaData();
// export const metadata = {
//   title: "",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{data?.data.title}</title>
        <meta name="description" content={data?.data.seo_description} />

      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
