import { Inter } from "next/font/google";
import "./globals.css";
import axios from "@/utils/axios";
import CustomCursor from "@/components/CustomCursor";

// const inter = Inter({ subsets: ["latin"] });

const getMetaData = async () => {
  try {
    const response = await axios.get("/page/home", {
      headers: {
        "Accept-Language": "en",
      },
    });
    return response.data;
  } catch (err) {
    console.error(err);
  }
};

const data = await getMetaData();
// export const metadata = {
//   title: "",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Georama:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <title>{data?.data.title}</title>
        <meta name="description" content={data?.data.seo_description} />
      </head>
      <body>
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
